In [1]:
import pandas as pd

# Task1
* Load a CSV dataset into a Pandas DataFrame.

In [2]:
df = pd.read_csv("tops.csv")
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,73.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,C-1███ 1S███LOO█████████3No███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,79.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,66.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937628_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
4,18979466,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,0,799.0,46.0,"""₹431.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""14.8in"",""value_name"":...",NaN,"Gro███ Fl███, 4█████████n A███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,NaN,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Nik███ndi███riv█████████ed,"[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","[""rw-18962100_cae700""]",Oly███a B███din█████████e T███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
118,18972666,MALHAAR,Yellow Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,70.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",JAI███MAR███OTH█████████TD,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",NaN,CIN███520███200█████████0 #███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,NaN,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",V-M███ Re███l L█████████,"[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...",NaN,Plo███o.8███ Se█████████Pha███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
121,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578.0,60.0,"""₹631.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Fly███,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",NaN,"Fla███o 6███jay█████████s, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

# Task 2
* Explore data (head/tail, shape, columns, data types)

In [3]:
df.head(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,73.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,C-1███ 1S███LOO█████████3No███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,79.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,66.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937628_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
4,18979466,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,0,799.0,46.0,"""₹431.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""14.8in"",""value_name"":...",NaN,"Gro███ Fl███, 4█████████n A███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
5,18972618,MALHAAR,Red Print Mandarin Collar Peplum Top,0.0,0,3329.0,79.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
6,18990292,HILL STREET,Women Fluorescent Green Solid Pure Cotton Tank...,4.5,15,1699.0,65.0,"""₹594.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",HIL███TRE███LIF█████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,"50,███OCK███ AS█████████PHA███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
7,18972748,Zink London,Yellow Geometric Print Top,4.3,7,1499.0,65.0,"""₹524.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,FRE███ GL███L P█████████MIT███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,"148███49,███0 A█████████lla███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
8,18998738,KALINI,Green & charleston green Animal Print Indigo Top,0.0,0,1999.0,74.0,"""₹519.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Oma███Ent███ris███,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""B...",NaN,PAR███NAT███ARA█████████ PL███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
9,18904492,Levis,Women Sage Green Self Design Slim Fit Regular Top,4.4,50,2099.0,20.0,"""₹1,133.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""XS"",""value"":""37.5in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",Eco███xpr███ Pv█████████no ███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [4]:
df.tail(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
112,11878498,DODO & MOA,Women Black Solid Top With Lace Inserts,3.9,9,1290.0,60.0,"""₹1,290.00""",INR,http://assets.myntassets.com/assets/images/118...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
113,7326508,MISH,Women Pink Solid Top,4.7,25,1499.0,45.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/732...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
114,586846,Cation,Women Black Top,4.5,11,899.0,40.0,"""₹899.00""",INR,http://assets.myntassets.com/v1/images/style/p...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
115,18000968,Harpa,Women Maroon V-Neck Casual Top,4.4,21,1049.0,48.0,"""₹1,049.00""",INR,http://assets.myntassets.com/assets/images/180...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""XS"",""value"":""30.0in"",""value_name"":""T...",NaN,NaN,"[{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
116,18937522,her by invictus,V-Neck Textured Regular Top,3.9,57,1298.0,65.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":4,""3_stars"":6,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, A Littl...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937522_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,NaN,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Nik███ndi███riv█████████ed,"[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","[""rw-18962100_cae700""]",Oly███a B███din█████████e T███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
118,18972666,MALHAAR,Yellow Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,70.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",JAI███MAR███OTH█████████TD,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",NaN,CIN███520███200█████████0 #███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,NaN,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",V-M███ Re███l L█████████,"[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...",NaN,Plo███o.8███ Se█████████Pha███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
121,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578.0,60.0,"""₹631.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Fly███,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",NaN,"Fla███o 6███jay█████████s, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
product_id,122.0,1.584558e+07,4.719283e+06,586846.0,1.359048e+07,17950203.0,18969964.50,22747068.0
rating,122.0,3.450000e+00,1.422212e+00,0.0,3.325000e+00,4.0,4.30,5.0
ratings_count,122.0,4.161475e+01,6.704969e+01,0.0,7.000000e+00,17.0,49.25,454.0
initial_price,122.0,1.578779e+03,7.533604e+02,329.0,9.990000e+02,1499.0,1998.75,3590.0
discount,107.0,5.466355e+01,1.775246e+01,5.0,4.550000e+01,60.0,65.00,82.0

In [6]:
df.describe(include='str').T

,count,unique,top,freq
title,122,69,MALHAAR,6
product_description,122,117,Women Pink Solid Top,3
final_price,122,65,"""₹1,499.00""",8
currency,122,1,INR,122
images,122,122,http://assets.myntassets.com/assets/images/186...,1
delivery_options,122,4,"[""100% Original Products"",""Pay on delivery mig...",113
product_details,122,122,"{""description"":"" Blue crop blouson top Soli...",1
breadcrumbs,122,69,"[{""name"":""Clothing"",""url"":""https://www.myntra....",6
product_specifications,122,122,"[{""specification_name"":""Body Shape ID"",""specif...",1
amount_of_stars,122,107,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",16
what_customers_said,84,61,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",14
seller_name,39,25,BED███E S███IES██████,6
sizes,122,107,"[{""size"":""XXS"",""value"":""30.0in"",""value_name"":""...",4
videos,18,18,"[""rw-18937628_cae700"",""https://videos.myntasse...",1
seller_information,39,25,1/4███Rii███Ind█████████rea███████████████████...,6
variations,51,13,"[{},{},{}]",12
best_offer,122,31,{},83
more_offers,122,2,"[{""offer_name"":""10% Instant Discount on Citi C...",84
category,122,1,tops,122

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              122 non-null    int64
 1   title                   122 non-null    str
 2   product_description     122 non-null    str
 3   rating                  122 non-null    float64
 4   ratings_count           122 non-null    int64
 5   initial_price           122 non-null    float64
 6   discount                107 non-null    float64
 7   final_price             122 non-null    str
 8   currency                122 non-null    str
 9   images                  122 non-null    str
 10  delivery_options        122 non-null    str
 11  product_details         122 non-null    str
 12  breadcrumbs             122 non-null    str
 13  product_specifications  122 non-null    str
 14  amount_of_stars         122 non-null    str
 15  what_customers_said     84 non-null     str
 16  seller_name             39 non-null     str
 17  sizes                   122 non-null    str
 18  videos                  18 non-null     str
 19  seller_information      39 non-null     str
 20  variations              51 non-null     str
 21  best_offer              122 non-null    str
 22  more_offers             122 non-null    str
 23  category                122 non-null    str
dtypes: float64(3), int64(2), str(19)
memory usage: 592.9 KB

In [8]:
df.shape

(122, 24)

In [9]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [10]:
df[["title","product_description","rating","final_price","delivery_options","discount"]]

,title,product_description,rating,final_price,delivery_options,discount
0,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,"""₹599.00""","[""100% Original Products"",""Pay on delivery mig...",73.0
1,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,"""₹699.00""","[""100% Original Products"",""Pay on delivery mig...",79.0
2,her by invictus,Printed A-Line Top,4.2,"""₹475.00""","[""100% Original Products"",""Pay on delivery mig...",66.0
3,MALHAAR,Green Print Wrap Top,0.0,"""₹732.00""","[""100% Original Products"",""Pay on delivery mig...",78.0
4,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,"""₹431.00""","[""100% Original Products"",""Pay on delivery mig...",46.0
...,...,...,...,...,...,...
117,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,"""₹2,495.00""","[""100% Original Products"",""Pay on delivery mig...",NaN
118,MALHAAR,Yellow Print Wrap Top,0.0,"""₹732.00""","[""100% Original Products"",""Pay on delivery mig...",78.0
119,Madame,Women Peach-Coloured Self Checked Top,3.6,"""₹479.00""","[""100% Original Products"",""Pay on delivery mig...",70.0
120,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,"""₹449.00""","[""100% Original Products"",""Pay on delivery mig...",NaN
121,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,"""₹631.00""","[""100% Original Products"",""Pay on delivery mig...",60.0

In [11]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

# Task 3
* Handle missing values (identify, fill/drop)

In [12]:
df.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
118,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
119,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
120,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,True,False,True,False,False,False
121,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False

In [13]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                   15
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said        38
seller_name                83
sizes                       0
videos                    104
seller_information         83
variations                 71
best_offer                  0
more_offers                 0
category                    0
dtype: int64

* Dropping Missing Values

In [14]:
df.dropna(axis=0)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
116,18937522,her by invictus,V-Neck Textured Regular Top,3.9,57,1298.0,65.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":4,""3_stars"":6,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, A Littl...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937522_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [15]:
df.dropna(axis=1)

,product_id,title,product_description,rating,ratings_count,initial_price,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,sizes,best_offer,more_offers,category
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue crop blouson top Soli...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Yellow and red regular peplu...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue and pink regular A-line t...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Green regular wrap top Eth...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
4,18979466,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,0,799.0,"""₹431.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" White and navy blue regular ...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""2-3Y"",""value"":""14.8in"",""value_name"":...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Special Technology:Engineered ...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":5,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
118,18972666,MALHAAR,Yellow Print Wrap Top,0.0,0,3329.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Yellow regular wrap topEthnic ...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Colour: peach-coloured regular...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":7,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Yellow blouson topSolidRound n...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":6,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
121,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578.0,"""₹631.00""",INR,http://assets.myntassets.com/assets/images/192...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black regular tank top Sol...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [16]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,73.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,C-1███ 1S███LOO█████████3No███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,79.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,66.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937628_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
4,18979466,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,0,799.0,46.0,"""₹431.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""14.8in"",""value_name"":...",NaN,"Gro███ Fl███, 4█████████n A███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,NaN,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Nik███ndi███riv█████████ed,"[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","[""rw-18962100_cae700""]",Oly███a B███din█████████e T███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
118,18972666,MALHAAR,Yellow Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,70.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",JAI███MAR███OTH█████████TD,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",NaN,CIN███520███200█████████0 #███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,NaN,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",V-M███ Re███l L█████████,"[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...",NaN,Plo███o.8███ Se█████████Pha███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
121,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578.0,60.0,"""₹631.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Fly███,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",NaN,"Fla███o 6███jay█████████s, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [17]:
df_filled = df.fillna(0)
df_filled

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,73.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",0,C-1███ 1S███LOO█████████3No███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,79.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,66.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937628_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
4,18979466,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,0,799.0,46.0,"""₹431.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""14.8in"",""value_name"":...",0,"Gro███ Fl███, 4█████████n A███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,0.0,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Nik███ndi███riv█████████ed,"[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","[""rw-18962100_cae700""]",Oly███a B███din█████████e T███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
118,18972666,MALHAAR,Yellow Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,70.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",JAI███MAR███OTH█████████TD,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",0,CIN███520███200█████████0 #███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,0.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",V-M███ Re███l L█████████,"[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...",0,Plo███o.8███ Se█████████Pha███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
121,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578.0,60.0,"""₹631.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Fly███,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",0,"Fla███o 6███jay█████████s, ███████████████████...",0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

# Task 4
* Perform basic operations (filter rows, select columns)

In [18]:
df_filled[df_filled['rating']>0]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,66.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937628_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
6,18990292,HILL STREET,Women Fluorescent Green Solid Pure Cotton Tank...,4.5,15,1699.0,65.0,"""₹594.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",HIL███TRE███LIF█████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",0,"50,███OCK███ AS█████████PHA███████████████████...",0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
7,18972748,Zink London,Yellow Geometric Print Top,4.3,7,1499.0,65.0,"""₹524.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,FRE███ GL███L P█████████MIT███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",0,"148███49,███0 A█████████lla███████████████████...",0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
9,18904492,Levis,Women Sage Green Self Design Slim Fit Regular Top,4.4,50,2099.0,20.0,"""₹1,133.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""XS"",""value"":""37.5in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",Eco███xpr███ Pv█████████no ███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
11,13583566,Chemistry,Navy Blue Regular Top with Embroidered Detail,4.5,20,1499.0,0.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/135...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",0,0,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""rw-13583566_cae700"",""https://videos.myntasse...",0,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,18000968,Harpa,Women Maroon V-Neck Casual Top,4.4,21,1049.0,48.0,"""₹1,049.00""",INR,http://assets.myntassets.com/assets/images/180...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",0,0,"[{""size"":""XS"",""value"":""30.0in"",""value_name"":""T...",0,0,"[{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
116,18937522,her by invictus,V-Neck Textured Regular Top,3.9,57,1298.0,65.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":4,""3_stars"":6,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, A Littl...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937522_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,0.0,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Nik███ndi███riv█████████ed,"[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","[""rw-18962100_cae700""]",Oly███a B███din█████████e T███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,70.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",JAI███MAR███OTH█████████TD,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",0,CIN███520███200█████████0 #███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,0.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",V-M███ Re███l L█████████,"[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...",0,Plo███o.8███ Se█████████Pha███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [19]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,73.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,C-1███ 1S███LOO█████████3No███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,79.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,66.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937628_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
4,18979466,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,0,799.0,46.0,"""₹431.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""14.8in"",""value_name"":...",NaN,"Gro███ Fl███, 4█████████n A███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,NaN,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Nik███ndi███riv█████████ed,"[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","[""rw-18962100_cae700""]",Oly███a B███din█████████e T███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
118,18972666,MALHAAR,Yellow Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,70.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",JAI███MAR███OTH█████████TD,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",NaN,CIN███520███200█████████0 #███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,NaN,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",V-M███ Re███l L█████████,"[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...",NaN,Plo███o.8███ Se█████████Pha███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
121,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578.0,60.0,"""₹631.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Fly███,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",NaN,"Fla███o 6███jay█████████s, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [20]:
df['final_price'] = pd.to_numeric(
    df['final_price']
    .str.replace('₹', '', regex=False)
    .str.replace('"', '', regex=False),
    errors='coerce'
)

In [21]:
df[(df['final_price'] > 500) & (df['final_price'] < 1000)]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,73.0,599.0,INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,C-1███ 1S███LOO█████████3No███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,79.0,699.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,78.0,732.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
5,18972618,MALHAAR,Red Print Mandarin Collar Peplum Top,0.0,0,3329.0,79.0,699.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
6,18990292,HILL STREET,Women Fluorescent Green Solid Pure Cotton Tank...,4.5,15,1699.0,65.0,594.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",HIL███TRE███LIF█████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,"50,███OCK███ AS█████████PHA███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
7,18972748,Zink London,Yellow Geometric Print Top,4.3,7,1499.0,65.0,524.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,FRE███ GL███L P█████████MIT███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,"148███49,███0 A█████████lla███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
8,18998738,KALINI,Green & charleston green Animal Print Indigo Top,0.0,0,1999.0,74.0,519.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Oma███Ent███ris███,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""B...",NaN,PAR███NAT███ARA█████████ PL███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
10,18972644,MALHAAR,Blue & Pink Floral Print Mandarin Collar Peplu...,0.0,0,3329.0,79.0,699.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
12,18551958,SHECZZAR,Women White & Black Striped Georgette Top,3.8,6,799.0,53.0,799.0,INR,http://assets.myntassets.com/assets/images/185...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
17,13573344,Roadster,The Lifestyle Co Black Solid Pure Cotton Regu...,4.0,280,699.0,NaN,699.0,INR,http://assets.myntassets.com/assets/images/135...,...,"{""1_star"":20,""2_stars"":17,""3_stars"":44,""4_star...","[{""percentage"":""79"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""33.5in"",""value_name"":""B...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
19,20222156,CODE by Lifestyle,Solid V-Neck Top,4.1,47,799.0,30.0,799.0,INR,http://assets.myntassets.com/assets/images/202...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":5,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""30.0in"",""value_name"":""B...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
20,20405594,AAHWAN,White Bralette Crop Top,3.2,166,999.0,50.0,999.0,INR,http://assets.myntassets.com/assets/images/204...,...,"{""1_star"":47,""2_stars"":13,""3_stars"":24,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""Onesize"",""value"":""26.0in"",""value_nam...",NaN,NaN,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
26,15888984,Friskers,Black Tank Top,0.0,0,978.0,42.0,567.0,INR,http://assets.myntassets.com/assets/images/158...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Fly███,"[{""size"":""S"",""value"":""30.0in"",""value_name"":""Bu...",NaN,"Fla███o 6███jay█████████s, ███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
29,18478530,Paralians,White Print peplum Top,3.7,454,999.0,50.0,999.0,INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":58,""2_stars"":35,""3_stars"":68,""4_star...","[{""percentage"":""59"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""T...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
36,17178948,FOREVER 21,Women Grey Solid Cloud Wash Crop Cotton Tank Top,4.4,11,1049.0,50.0,524.0,INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Wes███ry ███din█████████d_M██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,"Gro███ Fl███, N█████████old███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
37,17132266,Athena,Women Attractive Lime Green Solid Halter Neck Top,3.7,10,1499.0,64.0,539.0,INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,MAY███I L███STY█████████E L█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,P.N███61/███ Se█████████rga█████████████████████,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
41,18803468,Oxolloxo,White Geometric Top,0.0,0,1499.0,56.0,659.0,INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,KPA███PAR███ PR█████████ITE███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,C-1███ect███- 6█████████Utt█████████████████████,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
42,17253026,Athena,Green Floral Print Blouson Top,3.9,113,1699.0,70.0,509.0,INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":12,""2_stars"":8,""3_stars"":14,""4_stars...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",APE███PPA███S,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,"Plo███o. ███, P█████████2Se███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
43,22649882,IUGA,Notched Neck Short Sleeves Crop Top,3.0,6,1299.0,57.0,558.0,INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,ARB███R C███ECT██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,KH ███443███ND █████████C L███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
47,19018090,DressBerry,Burgundy Pure Cotton Solid Top,4.1,102,799.0,NaN,799.0,INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":11,""4_stars""...","[{""percentage"":""71"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
50,19018146,DressBerry,Women Green Solid Scoop Neck Fitted Top,4.0,110,899.0,56.0,899.0,INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":12,""2_stars"":11,""3_stars"":7,""4_stars...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
51,17268524,H&M,Women Brown Halter Neck Cropped Top,4.4,203,699.0,25.0,699.0,INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":6,""2_stars"":8,""3_stars"":12,""4_stars""...",NaN,NaN,"[{""size"":""XXS"",""value"":""30.0in"",""value_name"":""...",NaN,NaN,"[{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
54,18972596,MALHAAR,White & Brown Print Smocked Cinched Waist Top,0.0,0,3329.0,82.0,599.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
55,17124636,H&M,Women Grey Pure Cotton Cropped Top,3.7,25,799.0,25.0,799.0,INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":5,""2_stars"":2,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XXS"",""value"":""30.0in"",""value_name"":""...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
60,18980478,DEBONATELLA,White Print Ruffles Crepe Top,3.0,2,600.0,26.0,600.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""37.0in"",""value_name"":""Bu...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
62,18900376,DressBerry,Coffee Brown Pure Cotton Solid Top,3.7,332,699.0,NaN,699.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":43,""2_stars"":27,""3_stars"":64,""4_star...","[{""percentage"":""62"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
66,19017944,DressBerry,Rust Tank Top,4.1,94,799.0,NaN,799.0,INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":6,""2_stars"":3,""3_stars"":12,""4_stars""...",NaN,NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
67,17114132,HERE&NOW,Women Black Fitted Crop Top,4.1,51,999.0,NaN,999.0,INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":9,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""rw-17114132_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
71,18975854,Honey by Pantaloons,Blue & orchid tint Floral Print Linen Crop Top,0.0,0,1099.0,40.0,659.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Wes███ry ███din█████████d_P████████████,"[{""size"":""XS"",""value"":""35.0in"",""value_name"":""B...",NaN,Wes███ry ███din█████████e L███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
72,18849012,Fleximaa,Red & Blue Pack of 2 Pure Cotton Typography Lo...,0.0,0,1799.0,50.0,899.0,INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,FLE███LE ███ARE███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",NaN,"82,███VER███TRE█████████DUT███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
75,7206166,Mayra,Women Yellow Printed Top,2.4,34,895.0,70.0,895.0,INR,http://assets.myntassets.com/assets/images/720...,...,"{""1_star"":18,""2_stars"":1,""3_stars"":5,""4_stars""...","[{""percentage"":""34"",""value_name"":""Fit, Tight""}...",NaN,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
77,18944780,Miaz Lifestyle,Pack of 2 Peach-Coloured & Red Tops,2.7,3,1499.0,58.0,629.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Mia███ife███le,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",NaN,B-4███ubh███ Kh█████████lhi██████████████████,"[{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
79,17889776,CHIMPAAANZEE,White Striped Extended Sleeves Peplum Top,3.9,13,699.0,47.0,699.0,INR,http://assets.myntassets.com/assets/images/178...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Bu...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
82,17938374,CODE by Lifestyle,White & Turquoise Blue Floral Print Top,4.4,17,999.0,30.0,999.0,INR,http://assets.myntassets.com/assets/images/179...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""30.0in"",""value_name"":""B...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
89,7581747,Annabelle by Pantaloons,Women Blue Printed Top,4.3,50,899.0,25.0,899.0,INR,http://assets.myntassets.com/assets/images/758...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""36.0in"",""value_name"":""B...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
90,9818669,Globus,Women Pink Solid Top,4.3,8,999.0,60.0,999.0,INR,http://assets.myntassets.com/assets/images/981...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""B...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
94,9327149,Belle Fille,Women Grey Melange Solid Crop Top,3.8,4,999.0,50.0,999.0,INR,http://assets.myntassets.com/assets/images/932...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
96,18780000,Popwings,Yellow & sahara sun Floral Print Chiffon Empir...,3.7,31,1999.0,69.0,619.0,INR,http://assets.myntassets.com/assets/images/187...,...,"{""1_star"":5,""2_stars"":1,""3_stars"":6,""4_stars"":...",NaN,POP███GS ███OMM█████████ATE█████████,"[{""size"":""S"",""value"":""32.0in"",""value_name"":""To...",NaN,"Wz-███, A███, F█████████r,H███████████████████...","[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
99,8807033,Flying Machine,Women Blue Printed Pure Cotton Top,3.7,14,799.0,60.0,799.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
101,19024914,Miaz Lifestyle,Women Pack Of 2 Black & Peach-Coloured Crop Top,0.0,0,1499.0,56.0,659.0,INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Mia███ife███le,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",NaN,B-4███ubh███ Kh█████████lhi██████████████████,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
104,11811068,Honey by Pantaloons,Women Pink Floral Printed A-Line Top,4.4,15,999.0,35.0,999.0,INR,http://assets.myntassets.com/assets/images/118...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""B...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
106,17982570,H&M,Women Brown Lacing-Detail Cut-Out Top,4.5,52,999.0,25.0,999.0,INR,http://assets.myntassets.com/assets/images/179...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XXS"",""value"":""30.0in"",""value_name"":""...",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
111,11538822,Ajile by Pantaloons,Women Grey Melange Printed Top,4.2,17,599.0,8.0,599.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":3,""4_stars"":...","[{""percentage"":""80"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
114,586846,Cation,Women Black Top,4.5,11,899.0,40.0,899.0,INR,http://assets.myntassets.com/v1/images/style/p...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops

In [22]:
df[["title","product_description","rating","final_price","delivery_options","discount"]]

,title,product_description,rating,final_price,delivery_options,discount
0,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,599.0,"[""100% Original Products"",""Pay on delivery mig...",73.0
1,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,699.0,"[""100% Original Products"",""Pay on delivery mig...",79.0
2,her by invictus,Printed A-Line Top,4.2,475.0,"[""100% Original Products"",""Pay on delivery mig...",66.0
3,MALHAAR,Green Print Wrap Top,0.0,732.0,"[""100% Original Products"",""Pay on delivery mig...",78.0
4,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,431.0,"[""100% Original Products"",""Pay on delivery mig...",46.0
...,...,...,...,...,...,...
117,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,NaN,"[""100% Original Products"",""Pay on delivery mig...",NaN
118,MALHAAR,Yellow Print Wrap Top,0.0,732.0,"[""100% Original Products"",""Pay on delivery mig...",78.0
119,Madame,Women Peach-Coloured Self Checked Top,3.6,479.0,"[""100% Original Products"",""Pay on delivery mig...",70.0
120,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,449.0,"[""100% Original Products"",""Pay on delivery mig...",NaN
121,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,631.0,"[""100% Original Products"",""Pay on delivery mig...",60.0

# Task 5
* Remove Duplicates

In [23]:
df_filled.duplicated().sum()

np.int64(0)

In [24]:
df_filled.drop_duplicates(ignore_index=True)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,73.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",0,C-1███ 1S███LOO█████████3No███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,79.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,66.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937628_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
4,18979466,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,0,799.0,46.0,"""₹431.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""14.8in"",""value_name"":...",0,"Gro███ Fl███, 4█████████n A███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,0.0,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Nik███ndi███riv█████████ed,"[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","[""rw-18962100_cae700""]",Oly███a B███din█████████e T███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
118,18972666,MALHAAR,Yellow Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,70.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",JAI███MAR███OTH█████████TD,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",0,CIN███520███200█████████0 #███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,0.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",V-M███ Re███l L█████████,"[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...",0,Plo███o.8███ Se█████████Pha███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
121,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578.0,60.0,"""₹631.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Fly███,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",0,"Fla███o 6███jay█████████s, ███████████████████...",0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

* As in the csv file there are no duplicates, so to remove duplicates from any file we can use this method with example

In [25]:
df1 = pd.DataFrame({'Name':["Ajay","Kinshu","Ajay","Jatin"],'Marks':[85,92,85,93]})
df1

     Name  Marks
0    Ajay     85
1  Kinshu     92
2    Ajay     85
3   Jatin     93

In [26]:
df1.duplicated().sum()

np.int64(1)

In [27]:
df1_cleaned = df1.drop_duplicates(ignore_index=True)

In [28]:
df1_cleaned

     Name  Marks
0    Ajay     85
1  Kinshu     92
2   Jatin     93

# Task 6
* Create a derived column (total_amount = price * quantity).

In [29]:
df_filled

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,73.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",0,C-1███ 1S███LOO█████████3No███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,79.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,66.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937628_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
4,18979466,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,0,799.0,46.0,"""₹431.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""14.8in"",""value_name"":...",0,"Gro███ Fl███, 4█████████n A███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,0.0,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Nik███ndi███riv█████████ed,"[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","[""rw-18962100_cae700""]",Oly███a B███din█████████e T███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
118,18972666,MALHAAR,Yellow Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,70.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",JAI███MAR███OTH█████████TD,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",0,CIN███520███200█████████0 #███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,0.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",V-M███ Re███l L█████████,"[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...",0,Plo███o.8███ Se█████████Pha███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
121,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578.0,60.0,"""₹631.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Fly███,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",0,"Fla███o 6███jay█████████s, ███████████████████...",0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [30]:
df_filled.info()

<class 'pandas.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              122 non-null    int64
 1   title                   122 non-null    str
 2   product_description     122 non-null    str
 3   rating                  122 non-null    float64
 4   ratings_count           122 non-null    int64
 5   initial_price           122 non-null    float64
 6   discount                122 non-null    float64
 7   final_price             122 non-null    str
 8   currency                122 non-null    str
 9   images                  122 non-null    str
 10  delivery_options        122 non-null    str
 11  product_details         122 non-null    str
 12  breadcrumbs             122 non-null    str
 13  product_specifications  122 non-null    str
 14  amount_of_stars         122 non-null    str
 15  what_customers_said     122 non-null    object
 16  seller_name             122 non-null    object
 17  sizes                   122 non-null    str
 18  videos                  122 non-null    object
 19  seller_information      122 non-null    object
 20  variations              122 non-null    object
 21  best_offer              122 non-null    str
 22  more_offers             122 non-null    str
 23  category                122 non-null    str
dtypes: float64(3), int64(2), object(5), str(14)
memory usage: 566.4+ KB

In [31]:
import random
df_filled['quantity'] = [random.randint(1,10) for i in range(len(df_filled))]
df_filled['Total_amount'] = df_filled['final_price'] * df_filled['quantity']
df_filled

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,Total_amount
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,73.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",0,C-1███ 1S███LOO█████████3No███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,7,"""₹599.00""""₹599.00""""₹599.00""""₹599.00""""₹599.00""""..."
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,79.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,1,"""₹699.00"""
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,66.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,...,Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937628_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,1,"""₹475.00"""
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,8,"""₹732.00""""₹732.00""""₹732.00""""₹732.00""""₹732.00""""..."
4,18979466,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,0,799.0,46.0,"""₹431.00""",INR,http://assets.myntassets.com/assets/images/189...,...,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""14.8in"",""value_name"":...",0,"Gro███ Fl███, 4█████████n A███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,1,"""₹431.00"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,0.0,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,...,Nik███ndi███riv█████████ed,"[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","[""rw-18962100_cae700""]",Oly███a B███din█████████e T███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,1,"""₹2,495.00"""
118,18972666,MALHAAR,Yellow Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,8,"""₹732.00""""₹732.00""""₹732.00""""₹732.00""""₹732.00""""..."
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,70.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,...,JAI███MAR███OTH█████████TD,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",0,CIN███520███200█████████0 #███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,6,"""₹479.00""""₹479.00""""₹479.00""""₹479.00""""₹479.00""""..."
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,0.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,...,V-M███ Re███l L█████████,"[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...",0,Plo███o.8███ Se█████████Pha███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,4,"""₹449.00""""₹449.00""""₹449.00""""₹449.00"""
121,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578.0,60.0,"""₹631.00""",INR,http://assets.myntassets.com/assets/images/192...,...,Fly███,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",0,"Fla███o 6███jay█████████s, ███████████████████...",0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,5,"""₹631.00""""₹631.00""""₹631.00""""₹631.00""""₹631.00"""

In [32]:
df_filled.to_csv('Cleaned.csv',index=False)

In [33]:
df2 = pd.read_csv('Cleaned.csv')
df2

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,Total_amount
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,73.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",0,C-1███ 1S███LOO█████████3No███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,7,"""₹599.00""""₹599.00""""₹599.00""""₹599.00""""₹599.00""""..."
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,79.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,1,"""₹699.00"""
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,66.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,...,Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937628_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,1,"""₹475.00"""
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,8,"""₹732.00""""₹732.00""""₹732.00""""₹732.00""""₹732.00""""..."
4,18979466,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,0,799.0,46.0,"""₹431.00""",INR,http://assets.myntassets.com/assets/images/189...,...,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""14.8in"",""value_name"":...",0,"Gro███ Fl███, 4█████████n A███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,1,"""₹431.00"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,0.0,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,...,Nik███ndi███riv█████████ed,"[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","[""rw-18962100_cae700""]",Oly███a B███din█████████e T███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,1,"""₹2,495.00"""
118,18972666,MALHAAR,Yellow Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",0,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,8,"""₹732.00""""₹732.00""""₹732.00""""₹732.00""""₹732.00""""..."
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,70.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,...,JAI███MAR███OTH█████████TD,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",0,CIN███520███200█████████0 #███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,6,"""₹479.00""""₹479.00""""₹479.00""""₹479.00""""₹479.00""""..."
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,0.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,...,V-M███ Re███l L█████████,"[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...",0,Plo███o.8███ Se█████████Pha███████████████████...,0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,4,"""₹449.00""""₹449.00""""₹449.00""""₹449.00"""
121,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578.0,60.0,"""₹631.00""",INR,http://assets.myntassets.com/assets/images/192...,...,Fly███,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",0,"Fla███o 6███jay█████████s, ███████████████████...",0,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,5,"""₹631.00""""₹631.00""""₹631.00""""₹631.00""""₹631.00"""

## Summary

* In this assignment, we used the `tops.csv` dataset provided through the Kaggle resource.
* We loaded the CSV dataset using Pandas.
* After loading the dataset, we explored the data using built-in Pandas functions such as `describe()`, `info()`, `head()`, and `tail()`.
* We checked the dataset for missing (null) values in the DataFrame.
* The missing values were handled using the `fillna()` function in Pandas.
* We also checked for duplicate records and removed duplicate rows from the dataset.
* A new column named `Total_amount` was created using the `final_price` and `quantity` columns from the DataFrame.
    
    Total_amount = final_price x quantity
* Finally, the cleaned dataset was saved as a new CSV output file.